using System.Collections;
using System.Collections.Generic;
using UnityEngine;



public enum PacketTypeClient{
    PLAYER_KEYS,
    MOUSE_ROTATION_ANGLE,
    MESSAGE_ACKNOWLEDGMENT,
    CLIENT_INTRODUCTION,
    PLAYER_READY,
    CLIENT_ADMISSION_CONFIRMATION,
    START_GAME,

    PLAYER_KEY_MOVE_UP,
    PLAYER_KEY_MOVE_LEFT,
    PLAYER_KEY_MOVE_DOWN,
    PLAYER_KEY_MOVE_RIGHT,
    PLAYER_KEY_SHOOT,
    PLAYER_KEY_SHIELD,
    PLAYER_KEY_DODGE,

    TO_LOBBY,

    RELIABLE
}

public enum PacketTypeServer{
    CLIENT_ADMISSION_CONFIRMATION,
    PLAYER_INTRODUCTION,
    CLIENT_DISCONNECT,
    PLAYER_POSITION,
    PLAYER_ROTATION,
    PLAYER_ALIVE,
    PLAYER_NAME,
    PLAYER_ON_FIRE,
    PLAYER_ON_SPEED,
    PLAYER_MUNITION,
    PLAYER_SIDESTEP_READY,
    PLAYER_SHIELD_READY,
    PLAYER_SHIELD_ACTIVE,
    PLAYER_KILLS,
    PLAYER_WINS,
    PLAYER_KEYS,

    PLAYER_KEY_MOVE_UP,
    PLAYER_KEY_MOVE_LEFT,
    PLAYER_KEY_MOVE_DOWN,
    PLAYER_KEY_MOVE_RIGHT,

    PLAYER_KEY_DODGE,

    PLAYERS_TRANSFORM,
    PLAYER_TRANSFORM,

    PLAYER_READY,
    CONNECTION_CHECK,

    GAME_STATE,

    PROJECTILE_JOIN,
    PROJECTILE_LEAVE,
    PROJECTILES_TRANSFORM,
    PROJECTILE_POSITION,

    BOOSTPACKET_JOIN,
    BOOSTPACKET_POSITION,
    BOOSTPACKET_ROTATION,
    BOOSTPACKET_LEAVE,
    BOOSTPACKETS_TRANSFORM,

    MESSAGE_ACKNOWLEDGMENT,

    CLIENT_HOST,

    PLAYERS_UNREADY_ALL,

    RELIABLE
}

